GET https://query1.finance.yahoo.com/v1/finance/trending/US?count=5

###

GET https://query2.finance.yahoo.com/v7/finance/quote?symbols=UBER&fields=exchangeTimezoneName,exchangeTimezoneShortName,regularMarketTime,gmtOffSetMilliseconds&region=US&lang=en-US

###

GET https://query2.finance.yahoo.com/v7/finance/quote?symbols=AAAA